services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config

  debt:
    build:
      dockerfile: debt/Dockerfile
      context: .
    restart: always

  nebolive:
    build:
      dockerfile: nebolive-gateway-api/Dockerfile
      context: .
    env_file:
      - .env
    restart: always
