services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config

  debt:
    image: kiri11mi1/debt:latest
    ports:
      - "8000:8000"

#  nebolive:
#    image: kiri11mi1/nebolive:latest
#    ports:
#      - "8001:8080"
#    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
#    env_file:
#      - .env
