services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config

  debt:
    image: kiri11mi1/debt:latest
    restart: always

  nebolive:
    image: kiri11mi1/nebolive:latest
    env_file:
      - .env
    restart: always
